import time

from all_imports import *

class registerUser(unittest.TestCase):
    def setUp(self):
        driver.get("https://automationexercise.com/")
        time.sleep(3)

    def test_registerUser(self):
        actions = ActionChains(driver)
        driver.find_element(By.XPATH,"//a[@href='/login']").click()
        time.sleep(1)
        driver.find_element(By.XPATH,"//input[@name='name']").send_keys("test")
        driver.find_element(By.XPATH,"//input[@data-qa='signup-email']").send_keys("test@tests.com")
        time.sleep(1)
        driver.find_element(By.XPATH,"//button[@data-qa='signup-button']").click()
        time.sleep(1)
        print("first step completed, now redirected to account information tab")
        driver.find_element(By.XPATH,"//input[@id='id_gender1']").click()
        driver.find_element(By.XPATH, "//input[@id='password']").send_keys("test")
        time.sleep(1)
        days=driver.find_element(By.XPATH, "//select[@data-qa='days']")
        days.send_keys("5")
        time.sleep(0.5)
        #days.send_keys(Keys.ENTER)
        time.sleep(1)
        #actions.key_down(Keys.ENTER).perform()
        months=driver.find_element(By.XPATH, "//select[@data-qa='months']")
        months.send_keys("june")
        time.sleep(1)
        years=driver.find_element(By.XPATH, "//select[@data-qa='years']")
        years.send_keys("2024")
        time.sleep(1)
        driver.find_element(By.XPATH,"//input[@id='newsletter']").click()
        driver.find_element(By.XPATH,"//input[@id='optin']").click()
        driver.find_element(By.XPATH, "//input[@id='first_name']").send_keys("test")
        driver.find_element(By.XPATH,"//input[@id='last_name']").send_keys("test")
        driver.find_element(By.XPATH,"//input[@id='company']").send_keys("test")
        driver.find_element(By.XPATH,"//input[@id='address1']").send_keys("test")
        driver.find_element(By.XPATH, "//input[@id='address2']").send_keys("test")
        time.sleep(2)
        driver.find_element(By.XPATH, "//select[@id='country']").click()
        actions.key_down(Keys.ENTER).perform()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0, 500)")
        driver.find_element(By.XPATH,"//input[@data-qa='state']").send_keys("test")
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@data-qa='city']").send_keys("test")
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@data-qa='zipcode']").send_keys("test")
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@data-qa='mobile_number']").send_keys("121232435")
        time.sleep(1)
        driver.find_element(By.XPATH,"//button[@type='submit']").click()
        time.sleep(2)
        print("completed successfully")

    def tearDown(self):
        driver.close()
